### ISSUE TITLE
Super, danke! Cronjobs noch ein bisschen wackelig

### ISSUE THREAD

**Issue by hanshafner** [micha2el/fritz-dect#2]
Hallo Michael,

das ist echt ein super Script und ich freue mich voll, Daten zu sammeln. Vielen Dank für diese gute Arbeit!!

Als nächstes (nächste Woche vielleicht) werde ich mich dran wagen, auch das PowerGraph tool zum laufen zu bekommen.

Bei mir läuft das ganze seit gestern Abend auf einem Raspberry Pi, der läuft eh immer durch und zieht sich einfach die Daten.

Zu den Cronjobs:
wenn ich die manuell aufrufe, dann schreiben die schön ihre Daten in die entsprechenden Files, wenn allerdings cron sie aufruft passiert nichts.
Ich lasse das aber jetzt erst mal ein paar Tage laufen, um wirklich zu sehen, was so passiert, aber selbst der hourly macht nicht, was er soll. Außer manuell.

Irgendwas habe ich wohl noch falsch gemacht.

Beste Grüße
Hans

**Comment by hanshafner** [comment]
Ah, ich habe mir möglicherweise selbst geholfen...

Es scheint, dass beim reinkopieren die falschen Zeilenumbrüche erstellt wurden. Habe die rausgelöscht und neue reingemacht, jetzt scheint cron die Scripts zu laden.

**Comment by hanshafner** [comment]
Nein. Leider macht cron das wieder nicht.

Komisch ist nur, dass die 30 Sekunden Daten problemlos geschrieben werden, das dect-cron.sh aber nur funktioniert, wenn ich es manuell aufrufe.

**Comment by hanshafner** [comment]
Ok. Sehr merkwürdig.

so sieht jetzt das cronfile aus und so funktioniert es.

1 * * * * /bin/bash /home/USER/temperature-logging/dect-cron.sh -h
1 6 * * * /bin/bash /home/USER/temperature-logging/dect-cron.sh -d
1 6 1 * * /bin/bash /home/USER/temperature-logging/dect-cron.sh -m

* * * * * USER /home/USER/temperature-logging/dect-data-retrieval.sh
* * * * * USER sleep 30; /home/USER/temperature-logging/dect-data-retrieval.sh

keine Ahnung, warum ich das Hourly / Daily / Monthly script mit /bin/bash aufrufen muss während das dect-data-retrieval.sh auch funktioniert wenn ich es mit meinem User aufrufe.

Egal. So läuft es jetzt. Vielen Dank nochmal!

PS: Habe heute morgen damit verbraucht, mir in Python mittels matplotlib Graphen machen zu lassen. Das funktioniert ganz gut und war sehr sehr simpel. Braucht aber noch etwas Feinarbeit mit den Daten (Reduktion vor allem), der Auflösung und lesbaren Labels, aber fühlte sich für mich viel leichter zu realisieren an, als power graph mit den Dependencies etc... in die ich mich erst hätte voll einarbeiten müssen.

**Comment by micha2el** [comment]
Hallo Hans,

du warst ja schon erfolgreich, ohne, dass ich etwas gemacht habe. Prima :) Viel Spaß damit!

Mit Python hatte ich auch mal überlegt, aber ich war damals mit dem jpgraph schneller und wollte das sowieso mal ausprobieren ;) 

Schönen Gruß
Michael
